#!/usr/bin/env bash
# The script manages manage_my_process

PIDFILE=/var/run/my_process.pid

start() 
{
    ./manage_my_process &
    echo "$!" > "$PIDFILE"
}

stop() 
{
    sudo kill -15 "$(cat "$PIDFILE")" && rm -f "$PIDFILE"
}
case "$1" in 
    strt)
       start
       echo "manage_my_process started"
       ;;
    stp)
       stop
       echo "manage_my_process stopped"
       ;;
    restrt)
       stop
       start
       echo "manage_my_process restarted"
       ;;
    *)
       echo "Usage: manage_my_process {start|stop|restart}"
esac

exit 0
